### ISSUE TITLE
Nov 25th - Night before Turkey Day - Santa Fe Taproom

### ISSUE THREAD

**Issue by mark-casias** [beerjs/abq#28]
Discuss.

**Comment by ctm** [comment]
First, I rescind my advocacy for Knob Hill Bar and Grill. I finally got back there on Saturday and they no longer had any of the Avery beers on tap that I was so looking forward to revisiting. Ugh.

That said, the only time I've been to Santa Fe Taproom, it was crowded and noisy. I was also disappointed to learn that their specialty beers are not listed on the big chalkboard behind the bar, but on a different chalkboard to the left. I've learned that lesson, but it's a tidbit potentially worth sharing.

As usual, my vote should count but epsilon due to me not really doing much JavaScript, although I am actually paid to work on a Backbone + Marionette app. One of us? One of us?

**Comment by orbiteleven** [comment]
I have yet to visit the SFB tap. I'd be concerned that the Weds night before Thxgiving could be pretty busy. Or completely dead.

Let's see how many are interested in attending, then we can tune our location accordingly?

**Comment by orbiteleven** [comment]
Roll call for tomorrow

**Comment by mark-casias** [comment]
Will be there. A map, for those who don't want to do the googles: https://goo.gl/maps/1zDtkGXFayS2

**Comment by lordtangent** [comment]
I want to try this place so I will be there.

**Comment by ctm** [comment]
I'm on the fence. You going to be there, Damon?

**Comment by ianwcarlson** [comment]
I can make it.

**Comment by ianwcarlson** [comment]
I've got a decent head cold going on today so I'm probably skip tonight.

**Comment by orbiteleven** [comment]
Bummer @ianwcarlson! @ctm I'll be there. 🍺is always good.

Folks want to meet at 6 or 7?

**Comment by mark-casias** [comment]
I should be there at 6ish

**Comment by ctm** [comment]
OK. I'll be there at 6, too.

**Comment by samatjain** [comment]
I'll be around 5:30… happy hour ($3 pints) from 4–6 pm if anyone else is early.

**Comment by samatjain** [comment]
It's VERY busy… grabbed a table outside on the first floor. Look for a guy with a ThinkPad.

**Comment by samatjain** [comment]
Re: Javascript performance on Android: https://meta.discourse.org/t/the-state-of-javascript-on-android-in-2015-is-poor/33889

**Comment by mark-casias** [comment]
Closing
